### ISSUE TITLE
Friendly Namespace Prefix

### ISSUE THREAD

**Issue by cainelli** [kolihub/koli#16]
Namespaces prefix are added automatically by CLI. `koli get pods -n production` will look for namespace `{client_id}-production`.

Users, usually resellers, can specify a client ID to run commands to a specific namespace like `koli get pods -n {client_id}/production`.

Prefix must be user friendly if we want to give the ability to resellers perform delegated commands.

`koli get pods -n {client_name}/production`

Ideally, `{client_name}` can have the same name between different `resellers`, we would need to perform a lookup to find which `{client_id}` is actually the requested by `{client_name}` and `{reseller_id}`, information expected to be contained in TOKEN. Abstracting this, kubernetes namespace can continue to be as is today, `{client_id}-production` like the example above.

[slack_discussion.txt](https://github.com/kolibox/koli/files/480447/slack_discussion.txt)

**Comment by sandromello** [comment]
Related to #4

**Comment by sandromello** [comment]
Closed by #42, it's possible to validate and form a namespace using the information from the token.
