### ISSUE TITLE
Set *v1.DeleteOptions on deleting 3PR

### ISSUE THREAD

**Issue by sandromello** [kolihub/koli#59]
Due to a [bug](https://github.com/kubernetes/kubernetes/issues/37278) we're not able to pass *v1.DeleteOption deleting 3PR, wait for the new release to fix this issue (maybe 1.4.7)

**Comment by sandromello** [comment]
The patch is still on [master](https://github.com/kubernetes/kubernetes/blob/e732ee70f4ba4067fbcd22bb85b5b7ea146e5496/pkg/registry/extensions/thirdpartyresourcedata/codec.go#L373), wait for a release with that change

**Comment by nikinath** [comment]
Hi, the bug has been fixed. Please see: https://github.com/kubernetes/kubernetes/issues/37278#issuecomment-289780021 for further details. Works with `v1.5.2`.

**Comment by sandromello** [comment]
Thanks for the follow up @nikinath. I'm not using this option for deleting third party objects for now, this issue should be closed.
