### ISSUE TITLE
Kong Ingress not logging enough info on error

### ISSUE THREAD

**Issue by cainelli** [kolihub/koli#94]
Some critical log events only appears when we enable `--v=4` option. One example is the following:

```
I0401 19:42:11.366928       1 event.go:217] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"cainelli-bunny-acme", Name:"nodejs-app", UID:"b63df1b4-1712-11e7-899b-8665bab9fa6a", APIVersion:"extensions", ResourceVersion:"102169", FieldPath:""}): type: 'Warning' reason: 'FailedAddRoute' Get http://kong-admin:8001/apis/3ce9ff7fd89f7f427a097f31635604b3: dial tcp 10.100.169.120:8001: i/o timeout
```

Same for ingress events, it only creates the related event when the above flag was set.

**Comment by sandromello** [comment]
I've debugged the k8s events and found out that they are scoped to namespace, on this example you should view the events executing `kubectl get events -n cainelli-bunny-acme`. I will check it out the logging behaviour in kong-ingress.
